### ISSUE TITLE
Caffeinated has stopped working

### ISSUE THREAD

**Issue by ghost** [dmnd/Caffeinated#1]
Hello! I get this message when trying to run the program. I see program has not been updated in some time, could this be the cause?

Running Windows 7.

**Comment by dmnd** [comment]
Hello! Sorry for the late response.

This works fine for me on Windows 8.1, so I don't think it's broken due to any updates you may have. Do you have the .NET framework / runtime installed? Which version?

**Comment by ghost** [comment]
@dmnd I have .NET Framework 4.5

**Comment by dmnd** [comment]
Hmm. Does the error still occur if you run the app as an admin?

Without a more descriptive error it's tough to know what's wrong. If you're interested, you could run a debug build yourself and see what's causing the exception. I'm not sure how interested in debugging this you are though, so if you don't have time, no worries :)

**Comment by ghost** [comment]
The problem with Firefox that led to me wanting to use Caffeinated has been resolved
http://bugzilla.mozilla.org/show_bug.cgi?id=517870
